### PR TITLE
Compare password to allow pwd update

### PR DESCRIPTION
**Pull request by BarthV**
This little snippet tries to suggest a answer to #164

### CODE REVIEW

**Comment by BarthV** [comment]
We can debate here if password change code should be located in :action or :grant

**Comment by BackSlasher** [comment]
+1, Was just about to push a similar modification.
Might want to add a resource attribute like `maintain_password` which defaults to `false`, so it won't modify behavior for existing deployments

**Comment by BarthV** [comment]
Hi !

Adding a variable to control if we need to maintain password may be a good idea but ...
.. But I'm using this cookbook for a very long time, and in previous versions it has always supported the password control. Since multiples major breakdown in backward compatibility, this ability was lost and not rewrite as it worked previously :-/

V2 is now old, but you can look here : https://github.com/opscode-cookbooks/database/blob/v2.3.1/libraries/provider_database_mysql_user.rb#L61

If finally we really feel the need to set a control variable to this it should not be a huge work to do so.

**Comment by BackSlasher** [comment]
Didn't know that, nvm then :)

**Comment by BarthV** [comment]
thanks anyway :smile: !

**Comment by BarthV** [comment]
maybe we could support 40hexa char hashed password too ? ... like this cookbook did in V2.

**Comment by BarthV** [comment]
:up: :innocent: 
@someara ?

**Comment by alxndrmlr** [comment]
+1 was just hitting this challenge as well. 

I think it makes sense to be part of the grant as my gut reaction of the current behaviour was that there was a bug since I would change the desired password in my attributes file but it wasn't changing when I did a subsequent chef-run.

**Comment by BarthV** [comment]
:arrow_up_small: @someara @opscode-cookbooks/owners ?

**Comment by BarthV** [comment]
@tas50 ? any news ?

please :angel:

**Comment by tas50** [comment]
@BarthV I actually had to back this out. MySQL 5.7 removed the password column in favor of the authentication_string column.  If you want to refactor this in a way that would work with either setup I'm all for it, but right now it's breaking things.  There's a note on the change in these release notes:

https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html

**Comment by BarthV** [comment]
ok ! thanks for giving your time for this :)

**Pull request merged**
