### PR TITLE
Add SQL2008 alter_roles statement and fix alter_sys_roles for SQL2012+

### PR DESCRIPTION
**Pull request by petegallagher**
Hi,

There is currently no provision to add/drop roles for SQL2008.

Additionally the server role assignment for SQL2012 was incorrect.

Regards,

Peter

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by petegallagher** [comment]
Hi, 

I have signed the CLA but haven't heard anything back regarding this pull request. Can this be merged? 

Peter

**Comment by petegallagher** [comment]
@someara Is there any reason why this pull request cannot be merged? This fixes broken functionality on MSSQL 2008.

**Comment by burnzy** [comment]
:+1:

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tas50** [comment]
This should be fixed in #185 which was merged in.

**Pull request closed without merging**
