### PR TITLE
Add roles support to PostgreSQL user resource

### PR DESCRIPTION
**Pull request by axsuul**
This adds functionality to allow role attributes to be set for a PostgreSQL user. Example usage:

```ruby
postgresql_database_user "nomad" do
    connection postgres_connection
    password "keepitclassy"
    roles :superuser => true, :createdb => true
    action :create
end 
```

Let me know if anything needs to be cleaned up. I found this to be extremely useful so I hope it gets merged in!

### CODE REVIEW

**Comment by axsuul** [comment]
Will this ever be merged in?

**Comment by hardywu** [comment]
It takes way too long.

**Comment by gsaslis** [comment]
would be great if we could have this merged in guys! 
is there something I can do to help?

**Comment by axsuul** [comment]
Yes, can we get a confirmation that this will get merged in if we solve merge conflicts?

**Comment by gsaslis** [comment]
please ?  : )

**Comment by axsuul** [comment]
Just rebased... any word? :)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by gsaslis** [comment]
@axsuul guess that's a hint for you ;)

**Comment by axsuul** [comment]
@chef-supermarket I've signed the CLA a long time ago?

**Comment by gsaslis** [comment]
hmm guess it's probably one of the other authors of the commits included here?

**Comment by axsuul** [comment]
I'm not sure, can we get anyone from Chef to look into this please? @someara @tas50 @jtimberman

**Comment by tas50** [comment]
Since the CLA hasn't been signed in over 6 month for this PR I'm going to close it out at this point.  If the author would like to sign the CLA feel free to open up the PR again.

**Comment by axsuul** [comment]
@tas50 I have signed the CLA a long time ago and have contributed to official cookbooks before. I even get stickers and shirts from Chef because of this. This must be a mistake!

**Comment by tas50** [comment]
That's odd you do show up as authorized in supermarket.

**Comment by axsuul** [comment]
So does this mean it can get merged?

**Comment by ericgoedtel** [comment]
So is this possible at this point? Really useful to add the specified roles.

**Comment by ericgoedtel** [comment]
This looks like it is possible: https://github.com/chef-cookbooks/database/blob/b76d55c9bbeeb6b7d684b88f89f5801a29486a47/libraries/provider_database_postgresql_user.rb#L48

CTRL+F "superuser" and "createdb"

**Comment by gsaslis** [comment]
A real shame this never got merged in...  : (

perhaps a gentle :bump: would help?

**Comment by axsuul** [comment]
@gsaslis You can now achieve this without this pull request:

```ruby
postgresql_database_user user do
    superuser true
    createdb true
    action :create
end
```

Hope that works for you :) We can probably close this then.

**Comment by gsaslis** [comment]
@axsuul awesome!! thanks for the tip!!  : )

**Pull request closed without merging**
