### PR TITLE
Fix sql_role handling for database_sql_server_user

### PR DESCRIPTION
**Pull request by Annih**
Refactor the sql_role handling method and fix the following error:
> undefined local variable or method `sql_role`

In addition to the refactor it's also replace #152, #153 and #174

cc. @aboten

### CODE REVIEW

**Comment by Annih** [comment]
@tas50 there are many PR for the same fix, could we have one of them merged please?

**Comment by tas50** [comment]
@Annih Can you rebase this first?

**Comment by tas50** [comment]
nm I handled the merging. Thanks for the fix

**Comment by Annih** [comment]
Thanks @tas50

**Pull request merged**
